### PR TITLE
Create release-winget.yml

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` and `workflow` scopes as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @t1m0thyj.

### CODE REVIEW

**Comment by SpotlightForBugs** [comment]
I've looked at your code and I think it is 👍

**Comment by vedantmgoyal2009** [comment]
@t1m0thyj can you please merge? It has been a long time...

**Review by SpotlightForBugs — APPROVED** [review]

**Comment by t1m0thyj** [comment]
> @t1m0thyj can you please merge? It has been a long time...

Thanks for these changes and sorry for the delay. I plan to merge the PR soon to give it a try when the next version of WinDD is released. 🙂

**Comment by t1m0thyj** [comment]
@vedantmgoyal2009 @SpotlightForBugs I just released v5.2.1 and the workflow ran, but it doesn't look like it opened a PR: https://github.com/t1m0thyj/WinDynamicDesktop/actions/runs/4224863781

**Pull request merged**
