### PR TITLE
Added TimeZone and Fixed AnyCPU

### PR DESCRIPTION
**Pull request by poqdavid**
Well after using the app it crashed on me and I decided to try to fix it
so I added TimeZone cause in case you wanted the to use different TimeZone than the one on your system
also I think after updating the CefSharp it kind of broke AnyCPU but that's also sorted out
and I am not 100% sure of my changes you might want to test them a bit more even though I did do some tests my self

### CODE REVIEW

**Comment by poqdavid** [comment]
Also I should add idk why `sonar.login=` is invalid

**Comment by t1m0thyj** [comment]
@poqdavid Thanks for your PR!

> so I added TimeZone cause in case you wanted the to use different TimeZone than the one on your system

Could you provide more detail explaining why this is a useful feature for you? My initial thought is that the app doesn't need a timezone option, as its purpose is to reflect the user's current location and timezone.

> also I think after updating the CefSharp it kind of broke AnyCPU but that's also sorted out

The build needs to be AnyCPU in order for ARM users to be able to run WDD. I configured the project so it should be able to build in AnyCPU mode using only the x86 CEF DLLs. Could you provide more detail about the build problem you encountered related to CefSharp?

> Well after using the app it crashed on me and I decided to try to fix it

I think the scope of this PR should be limited to fixing the crash you experienced. The other changes above can be added in separate PRs. Please provide more details about the crash, as I'm not sure if it was CefSharp or timezone related.

> Also I should add idk why sonar.login= is invalid and for Python I didn't know if u prefer 32bit or 64bit so I kept both

I'll look into the AppVeyor build and fix it in master branch, then you can pull that fix into your branch. 🙂

**Comment by poqdavid** [comment]
> Could you provide more detail explaining why this is a useful feature for you? My initial thought is that the app doesn't need a timezone option, as its purpose is to reflect the user's current location and timezone.

Well not all cases user's pc is using their timezone and also set by default the modification I added it gets the user's default timezone so this gives user the option to change the timezone in the case for whatever the reason that the user didn't had the proper timezone set in their pc they still will be able to use the app


> The build needs to be AnyCPU in order for ARM users to be able to run WDD. I configured the project so it should be able to build in AnyCPU mode using only the x86 CEF DLLs. Could you provide more detail about the build problem you encountered related to CefSharp?

Well not sure what happened maybe packages got update or something but anyways it just could't load the CefSharp dlls but its fine now with a bit of change its working ok

> I think the scope of this PR should be limited to fixing the crash you experienced. The other changes above can be added in separate PRs. Please provide more details about the crash, as I'm not sure if it was CefSharp or timezone related.

Well the crash was timezone related cause i use GMT timezone but i am not actually in that timezone and then as i said up there when i tried to build CefSharp dlls didnt wanted to load but its fine now

> I'll look into the AppVeyor build and fix it in master branch, then you can pull that fix into your branch. 🙂

Cool all of its fine now but the only part that doesnt work is 

`'if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { & dotnet sonarscanner end /d:sonar.login="$env:SonarQubeToken" }'`

Also sorry for the mess xD with commits and everything

**Comment by poqdavid** [comment]
@t1m0thyj No Problem happy to help :)

> Could you provide more detail explaining why this is a useful feature for you? My initial thought is that the app doesn't need a timezone option, as its purpose is to reflect the user's current location and timezone.

Well not all cases user's pc is using their timezone and also set by default the modification I added it gets the user's default timezone so this gives user the option to change the timezone in the case for whatever the reason that the user didn't had the proper timezone set in their pc they still will be able to use the app


> The build needs to be AnyCPU in order for ARM users to be able to run WDD. I configured the project so it should be able to build in AnyCPU mode using only the x86 CEF DLLs. Could you provide more detail about the build problem you encountered related to CefSharp?

Well not sure what happened maybe packages got update or something but anyways it just could't load the CefSharp dlls but its fine now with a bit of change its working ok

> I think the scope of this PR should be limited to fixing the crash you experienced. The other changes above can be added in separate PRs. Please provide more details about the crash, as I'm not sure if it was CefSharp or timezone related.

Well the crash was timezone related cause i use GMT timezone but i am not actually in that timezone and then as i said up there when i tried to build CefSharp dlls didnt wanted to load but its fine now

> I'll look into the AppVeyor build and fix it in master branch, then you can pull that fix into your branch. 🙂

Cool all of its fine now but the only part that doesnt work is 

`'if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { & dotnet sonarscanner end /d:sonar.login="$env:SonarQubeToken" }'`

Also sorry for the mess xD with commits and everything

**Comment by poqdavid** [comment]
@t1m0thyj Do want a more specific PR?

**Comment by poqdavid** [comment]
Sorry I tried to fix the conflict by adding ur changes but clearly it didn't work

**Comment by poqdavid** [comment]
@t1m0thyj I am stuck with a problem everything is fine when the location option is used with the changes I made but when the user-defined time is used the `GetUserProvidedSolarData()` gets the data wrong and the application it says its night while it's like 8AM

**Comment by poqdavid** [comment]
@t1m0thyj 
I changed the `ScheduleDialog` a bit more added latitude and longitude input for the user that it also gets populated by the other location options
I made those changes because I noticed that the `GetUserProvidedSolarData` throws an error in some cases but `GetSolarData` itself is fine cause I figured for the solar data making lat and lng a requirement would be better makes it more accurate and stable

Also, not sure if you want this PR since you haven't said anything else, I keep updating it so yah please let me know

**Comment by t1m0thyj** [comment]
Sorry for taking so long to reply. Closing this PR as IMO the addition of a timezone option doesn't seem necessary.

If you want the schedule of WDD to follow a different timezone than your system clock, then you can input a location that's in that timezone. If WDD is crashing because of your timezone, then that's a separate bug to report.

**Pull request closed without merging**
