### PR TITLE
Porting from .NET Framework 4.7.2 to .NET 5.0

### PR DESCRIPTION
**Pull request by sungaila**
## .NET Framework is dead, long live .NET!

* SDK format is used for the csproj file
* ~AssemblyInfo is removed (it's part of the csproj now)~
* App.config removed
* `HttpEnvironmentProxy` removed and replaced by [`HttpClient.DefaultProxy`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=net-5.0)
* [C#/WinRT](https://github.com/microsoft/CsWinRT) is used for WinRT APIs (like location services)
* [Costura.Fody](https://github.com/Fody/Costura) removed
  * Doesn't work with C#/WinRT and can be replaced by [single-file executables](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#single-file-executables) and [assembly linking](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#single-file-executables) anyway
* Added **Any CPU** target
  * The [.NET 5.0 runtime](https://dotnet.microsoft.com/download/dotnet/5.0/runtime) must be installed for this target
* Added **x86** and **x86-64** standalone targets
  * These are needed for the Windows Store app; no installed .NET runtime required
* Added **PerMonitorV2** to the app manifest
  * The UI can be resized for all given DPI (think about dragging windows between monitors)
  * The app was just system DPI aware before that
* Added *.user to gitignore
* Replace [`NamedPipeWrapper`](https://github.com/acdvorak/named-pipe-wrapper) with [`System.IO.Pipes`](https://docs.microsoft.com/de-de/dotnet/api/system.io.pipes?view=net-5.0)

## Drawbacks
* You need the .NET 5.0 SDK to develop this app (can be installed via Visual Studio Installer)
* The standalone apps for the Windows Store contain the entire runtime (.NET 5, WinForms and WPF) - that's huge!
  * 77 MB for x86
  * 83 MB for x64
  * 161 MB as msixbundle (both x86 and x86-64)
* Windows 7 SP1 or newer is needed
  * For location serivces Windows 10 Version 1809 (17763.0) or newer is needed

### CODE REVIEW

**Comment by sungaila** [comment]
.NET 6 includes a port of WPF for ARM64 (#225). Upgrading from .NET 5 to .NET 6 will be trivial.

**Comment by sungaila** [comment]
Oh, and the scripts for AppVeyor need to be modified (e.g. there is no AssemblyInfo.cs to manipulate). I will look into it.

**Comment by t1m0thyj** [comment]
Thanks for doing this migration! I'm sure this will be a big help in the future when I want to update WDD to .NET 5. I don't think I want to do this update yet for reasons described below, but I'm happy to keep this PR open for a while until I'm ready to do it 🙂 

Until .NET 5 (or 6) supports native GUIs on ARM, I don't have enough reason to leave .NET Framework. I still want to support older versions of Windows like 7 and 8. This may seem silly since Microsoft has stopped supporting them, but they still make up a significant fraction ([~20%](https://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide)) of Windows users, and I know personally some WDD users who still run Win 7 and 8.

Regarding the "PerMonitorV2" DPI setting, I can already do this with .NET Framework 4.7, and thought WDD was already doing so but thanks to you I realized there was a DPI-related bug. It should now be fixed in https://github.com/t1m0thyj/WinDynamicDesktop/commit/2376aea39e0388c019deda34205c8e1811f9c0b3. I'll look into moving the DPI configuration into the app manifest since it's the recommended method - previously I thought I had a reason for calling APIs instead, but now I'm unsure why.

**Comment by t1m0thyj** [comment]
One more thing about upgrading to .NET 5 - I believe the HttpEnvironmentProxy.cs can be deleted and replaced with [`System.Net.Http.HttpClient.DefaultProxy`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=net-5.0).

**Comment by sungaila** [comment]
Fair enough, but you don't have to leave Windows 7/8 users behind. .NET 5.0 supports Windows 7 SP1 and newer. However, the target framework can't be `net5.0-windows10.0.17763.0` and the location API call must be hidden behind a feature switch.

WinForms and WPF should be Per-monitor aware by default since 4.6.1 (?). Unless you force system DPI awareness with your manifest. 😉

**Comment by t1m0thyj** [comment]
> Fair enough, but you don't have to leave Windows 7/8 users behind. .NET 5.0 supports Windows 7 SP1 and newer. However, the target framework can't be `net5.0-windows10.0.17763.0` and the location API call must be hidden behind a feature switch (C#/WinRT is Win10 exclusive I think).

What target framework would you suggest using then? Curious why in this PR you switched to the one that requires Win10 rather than using a more compatible one.

The UWP location API shouldn't be a problem as it's lazy loaded, and WDD never calls it on Win 7/8.

**Comment by sungaila** [comment]
> Curious why in this PR you switched to the one that requires Win10 rather than using a more compatible one.

Just for convenience because this will expose WinRT APIs easily withot additional work.

I think the best option would be switching to `net5.0-windows` as target, include the NuGet packages for WinRT and calling the position API in a switch. No need for multiple framework targets.

I'll create a commit for this but will have to setup my Win7 VM first. 😄

**Comment by sungaila** [comment]
* Readded `AssemblyInfo.cs` so`prebuild_appveyor.ps1` doesn't have to be updated
* Switched to `HttpClient.DefaultProxy`

I tested the binaries on Windows 7 and they worked just fine. Turns out you can target `net5.0-windows10.0.17763.0` as long as you don't call the WinRT APIs. Neat!

image
image

However, I just noticed that WDD started to utilize an entire virtual processor for no reason. Windows Forms calls `ComponentManager.FPushMessageLoop` and 98% of CPU cycles are wasted in some unmanged kernel function. Looking into it right now ...

**Comment by sungaila** [comment]
I am not familiar with AppVeyor and where to configure it. It looks like it fails to create the Windows Store packages.

This should be a simple config issue. The Package project must be build with **x86** and **x64** as targets, the target **neutral** is not supported anymore (you can't create a neutral and x64 build at the same time).

Fun fact: Building a .NET project as neutral for the Windows Store will result in a x86 build.

**Comment by sungaila** [comment]
@t1m0thyj FYI, both WPF and WinForms for ARM64 have been [backported to .NET 5.0.8](https://devblogs.microsoft.com/dotnet/net-july-2021/#windows-arm64). So there is no need to wait for the .NET 6.0 release!

I failed at building WDD as ARM64 in my recent attempt but I would take a look at it once more.

**Comment by t1m0thyj** [comment]
Thanks so much for your work on this! ❤️ Merging now into a feature branch, I'll look into fixing the AppVeyor build and making any other necessary tweaks before merging into develop branch.

**Pull request merged**
