### PR TITLE
Replace CefSharp previewer with WPF

### PR DESCRIPTION
**Pull request by cjvaughter**
Easier to use and deploy, much lighter on resources, and doesn't flicker.

I've tested this in as many scenarios as I can, but you still may want to do some inspection yourself.

Let me know if you have any questions.

### CODE REVIEW

**Comment by t1m0thyj** [comment]
Thanks for doing this! After taking a quick look, I agree with your assessment:
> Easier to use and deploy, much lighter on resources, and doesn't flicker.

However I have a few concerns/questions:
* How well do the transitions between images work on your machine? I don't see much of a fade happening at all, compared to the CefSharp previewer.
* For large images (e.g., Big Sur preview after the theme is downloaded), the image scaling seems to result in noticably poorer quality (the water looks grainier in the WPF image):

  **CefSharp**
  image

  **WPF**
  image

**Comment by cjvaughter** [comment]
No problem!

Not fading is... odd. It Works On My Machine ™
It's definitely supposed to fade. I'll see what I can figure out.

As for the quality, I completely forgot to set any rendering options, so I'll fix that.

**Comment by cjvaughter** [comment]
### Render Quality
Easy enough, I just set the BitmapScalingMode to "Fant."

### Fading
Previously, the fade animation did not wait for the image to load before starting. For normal images this wasn't a problem, but for very large ones (or in the case of slow disk access) the animation would be ~90-100% done before the image "popped in." 

So now we just preload the image data. However, images in WPF do not really "load" until they are actually rendered. So instead of starting the animation directly, we have to start a short timer (to allow a frame or two to be drawn) which will then trigger the animation. It's a little hacky, but there doesn't appear to be another way to do this easily.

**Comment by t1m0thyj** [comment]
Thanks again for doing this! I haven't used WPF before but this method seems superior to using CefSharp and I'd like to use it in WDD once it's a bit more polished.

The fading works much better for me now. A few comments:
* There seems to be an issue with the 5th image in the Big Sur sequence taking a long time to load (only the first time it loads after starting WDD). I don't think this is a problem with your code, as other themes appear fine. There seems to be something about that particular image which causes problems when it is loaded on Windows: https://github.com/t1m0thyj/WinDynamicDesktop/issues/216
* I'd like to keep the following behavior of the Bootstrap carousel:
  * Hovering mouse anywhere over the image should pause the carousel cycling and make it stay on current image
  * When the mouse leaves the image, the image should resume cycling every X seconds
* When the carousel indicators are disabled (which happens during theme download process), their background should be transparent but isn't:
  image

**Comment by cjvaughter** [comment]
I use WPF quite a bit at work, so I'm pretty familiar with it. I'd be happy to assist with the conversion if you're interested. WinForms is capable enough, but data binding and control templating make WPF really powerful and easy to use once you're used to it (minus a few 'gotcha' items here and there).

Glad the fading is better. I appreciate you checking all this. It can be difficult to find certain issues.

- Big_Sur_5.jpg doesn't cause any trouble for me at all. I'm on 2004 19401.508. 🤷🏼‍♂️
- I actually didn't even notice that behavior. That should be easy to fix.
- I hadn't noticed that either. That's not supposed to happen.

**Comment by cjvaughter** [comment]
Okay everything should be working now.

**Comment by t1m0thyj** [comment]
@cjvaughter Thanks for the quick fixes! The WPF control now seems polished enough that I'm happy to merge it.

> I use WPF quite a bit at work, so I'm pretty familiar with it. I'd be happy to assist with the conversion if you're interested. WinForms is capable enough, but data binding and control templating make WPF really powerful and easy to use once you're used to it (minus a few 'gotcha' items here and there).

Thanks for the offer, I'll keep that in mind. I can see a lot of benefits to having the theme previewer implemented in WPF like you did. Not sure whether it would be worthwhile to convert the rest of the app as I think WinForms is working ok for the rest of the UI currently. Feel free to send me an email (my address is on GitHub profile), and we can discuss WPF more in the future (via email, Discord, Telegram, etc).

**Pull request merged**
