### PR TITLE
Add Auto Dark Mode

### PR DESCRIPTION
**Pull request by jeanoskii**
Added a feature to automatically change Windows system and app themes from light to dark and vice versa, based on user defined sunset and sunrise times.

### CODE REVIEW

**Comment by leostudiooo** [comment]
Seems we've got the same feature with the scripts at [t1m0thyj/WDD-scripts `/stable`](https://github.com/t1m0thyj/WDD-scripts/tree/master/stable) with a similar implement.

Have you tested it yet whether it has the same problem(#427) like those scripts do? Maybe only changing registry doesn't work anymore.

**Comment by jeanoskii** [comment]
I wasn't aware about the scripts thing honestly. It wasn't touted as a feature in the WDD Github page, so I went ahead and implemented an Auto Dark Mode feature as part of the icon menu.

**Comment by leostudiooo** [comment]
I've checked your code and it's the same implement as the script's (by writing the registry key), so it probably has the same issue.

**Comment by jeanoskii** [comment]
I'll check if my implementation resolves #427

**Comment by t1m0thyj** [comment]
@jeanoskii Thanks for your contribution!

This feature is already implemented in the WDD-scripts repo, and I don't plan to add features unrelated to dynamic wallpaper into the core app.

For that reason I'm closing this PR, but would welcome a few other contributions:
> I wasn't aware about the scripts thing honestly. It wasn't touted as a feature in the WDD Github page
* A PR that updates the WDD GitHub page to mention scripts more prominently would be welcome.
> I've checked your code and it's the same implement as the script's (by writing the registry key), so it probably has the same issue.
* A PR that updates the ChangeWindowsAppTheme and ChangeWindowsSystemTheme scripts to fix this issue would also be welcome.

**Pull request closed without merging**
